apiVersion: v1
kind: Service
metadata:
  name: demo-devops-python
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
  selector:
    app: demo-devops-python
